import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Petk Documentation Sidebar Configuration
 * Organized using the Diátaxis framework for optimal user experience
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar organized by user intent
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: '📚 Learning',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'learning',
        },
      ],
    },
    {
      type: 'category',
      label: '🔧 Problems',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'problems',
        },
      ],
    },
    {
      type: 'category',
      label: '📖 Reference',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference',
        },
      ],
    },
    {
      type: 'category',
      label: '💡 Explanation',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'explanation',
        },
      ],
    },
  ],
};

export default sidebars;
