name: PR Validation

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: read

jobs:
  validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ['22', '23', 24']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate Changesets
        run: |
          base_sha=${{ github.event.pull_request.base.sha }}
          head_sha=${{ github.event.pull_request.head.sha }}
          changed_files=$(git diff --name-only $base_sha $head_sha)
          has_package_changes=$(echo "$changed_files" | grep -E '^apps/|^packages/' || true)
          has_changeset=$(echo "$changed_files" | grep '^\\.changeset/' || true)
          if [ -n "$has_package_changes" ] && [ -z "$has_changeset" ]; then
            echo "❌ Changes detected in apps or packages but no changeset added. Please run 'pnpm changeset' to add one."
            exit 1
          fi
          echo "✅ Changesets validated"

      - name: Run lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

      - name: Build packages
        run: pnpm run build

      - name: Check for build artifacts
        run: |
          if [ ! -d "apps/cli/dist" ]; then
            echo "❌ Build artifacts not found in apps/cli/dist"
            exit 1
          fi
          echo "✅ Build artifacts verified"

      - name: Validate package.json versions
        run: |
          # Ensure package.json files have consistent structure
          if [ ! -f "apps/cli/package.json" ]; then
            echo "❌ apps/cli/package.json not found"
            exit 1
          fi
          echo "✅ Package structure validated"

  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: pnpm audit --audit-level moderate

      - name: Check for security vulnerabilities
        run: |
          # Check for common security issues in dependencies
          if pnpm audit --audit-level high --json | grep -q '"vulnerabilities"'; then
            echo "❌ High severity vulnerabilities found"
            pnpm audit --audit-level high
            exit 1
          fi
          echo "✅ No high severity vulnerabilities found"